import { createElement } from '@lwc/engine-dom';
import Lwc_test2_w_ldt from 'c/lwc_test2_w_ldt';

describe('c-lwc-test2-w-ldt', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-test2-w-ldt', {
            is: Lwc_test2_w_ldt
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});